sudo: false

language: java
jdk: oraclejdk8

script: mvn clean verify -B

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/57219697b0fbfc906418
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false

after_success:
  - mvn clean test jacoco:report coveralls:report
