main: me.gnat008.perworldinventory.PerWorldInventory
version: maven-version
name: PerWorldInventory
author: Gnat008
softdepend: [Vault]

commands:
  pwi:
    description: Commands for PerWorldInventory
    aliases: [perworldinventory]

permissions:
  perworldinventory.admin:
    default: op
    children:
      perworldinventory.convert: true
      perworldinventory.help: true
      perworldinventory.reload: true
      perworldinventory.setdefaults: true
      perworldinventory.version: true
  perworldinventory.bypass.*:
    default: false
    children:
      perworldinventory.bypass.gamemode: true
      perworldinventory.bypass.world: true
  perworldinventory.useLastPosition.*:
    default: true
    children:
      perworldinventory.useLastPosition.worldInGroup: true
      perworldinventory.useLastPosition.locationInWorld: true
  perworldinventory.convert:
    default: false
  perworldinventory.help:
    default: false
  perworldinventory.reload:
    default: false
  perworldinventory.setdefaults:
    default: false
  perworldinventory.version:
    default: false
  perworldinventory.bypass.gamemode:
    default: false
  perworldinventory.bypass.world:
    default: false
  perworldinventory.useLastPosition.worldInGroup:
    default: true
  perworldinventory.useLastPosition.locationInWorld:
    default: true
