main: ${project.groupId}.perworldinventory.${project.artifactId}
version: ${project.version}
name: ${project.name}
author: Gnat008
softdepend: [Vault]

commands:
  pwi:
    description: Commands for PerWorldInventory
    aliases: [perworldinventory]
    
permissions:
  perworldinventory.admin:
    default: op
    children:
      perworldinventory.convert: true
      perworldinventory.reload: true
      perworldinventory.setdefaults: true
  perworldinventory.convert:
    default: false
  perworldinventory.reload:
    default: false
  perworldinventory.setdefaults:
    default: false
