main: me.gnat008.perworldinventory.PerWorldInventory
version: maven-version
name: PerWorldInventory
website: http://dev.bukkit.org/bukkit-plugins/world-inventory/
author: Gnat008
softdepend: [Vault]

commands:
  pwi:
    description: Commands for PerWorldInventory
    aliases: [perworldinventory]
    
permissions:
  perworldinventory.admin:
    default: op
    children:
      perworldinventory.convert: true
      perworldinventory.reload: true
      perworldinventory.setdefaults: true
  perworldinventory.convert:
    default: false
  perworldinventory.reload:
    default: false
  perworldinventory.setdefaults:
    default: false
